<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <h2>EXP 1</h2>
    <h2>Date:16/07/2024</h2>
    <h2>Reg No:URK22CS5090</h2><br>
    <center><h1>Working with Python Data Structures</h1></center>
    <h4>Aim</h4>
    <p>Write a python program to demonstrate the basics of dictionary, list, set, tuple, array and
csv files for data science application.</p>
    <h4>Description</h4>
    <p><b>Lists:</b><br>

Lists are mutable data types in Python. Lists is a 0-based index datatype meaning the index
of the first element starts at 0. Lists are used to store multiple items in a single variable.
Lists are one of the 4 data types present in Python

<b>Dictionary:<b><br>

Dictionaries are mutable data types in nature meaning they can be updated after they are
created. Syntactically they are written in a key, value pair format inside curly braces.
{Key1:Value1,Key2:Value2,Key3:Value3,Key4:Value4}
Keys are always unique and there cannot be any duplicates. There is no index in the
dictionary meaning they are not ordered. Key is the default iterator and is used to retrieve
the value.

<b>Tuple:</b><br>

Tuples are the same as lists are with the exception that the data once entered into the tuple
cannot be changed no matter what. The only exception is when the data inside the tuple is
mutable, only then the tuple data can be changed
Creating a Tuple
Tuple is created by using parenthesis or using the tuple() function.
my_tuple = (1, 2, 3) #create tuple
print(my_tuple)
Output:
(1, 2, 3)

<b>Sets:</b><br>
    
Sets are a collection of unordered elements that are unique. Meaning that even if the data is
repeated more than one time, it would be entered into the set only once. It resembles the
sets that you have learnt in arithmetic. The operations also are the same as is with the
arithmetic sets.
Creating a set
Sets are created using the flower braces but instead of adding key-value pairs, values are
passed into it.
my_set = {1, 2, 3, 4, 5, 5, 5} #create set
print(my_set)
Output:
{1, 2, 3, 4, 5}

<b>CSV Files:</b><br>
    
CSV stands for “Comma Separated Values.” It is the simplest form of storing data in tabular
form as plain text. It is important to know to work with CSV because we mostly rely on
CSV data in our day-to-day lives as data scientists.</p>
</body>
</html>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>1. Create an empty dictionary. Fill the dictionary with prod_code and prod_name as pair
by user input (Use prod_code as a key). Take one prod_code as input from the user and
traverse through dictionary to find the corresponding prod_name and display the same.</p></b>
</body>
</html>

In [1]:
dict = {}
n = int(input("Enter the number of products: "))
for _ in range(n):
    code = input("Enter product code: ")
    name = input("Enter product name: ")
    dict[code] = name
print("The product dictionary is:", dict)
search_code = input("Enter the product code to search for: ")
if search_code in dict:
    print(f"The product name for code '{search_code}' is: {dict[search_code]}")
else:
    print(f"No product found for code '{search_code}'")



Enter the number of products:  3
Enter product code:  101
Enter product name:  Acer
Enter product code:  102
Enter product name:  Asus
Enter product code:  103
Enter product name:  Dell


The product dictionary is: {'101': 'Acer', '102': 'Asus', '103': 'Dell'}


Enter the product code to search for:  102


The product name for code '102' is: Asus


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>2.Create an empty list. Fill the list with strings by getting user input. Find the list of words
that are longer than n from a given list of words.<br>
Sample List : [‘the’,’quick’,’brown’,’fox’]<br>
n : 3<br>
Expected Result : quick brown</p></b>
</body>
</html>

In [2]:
lst=[]
n=int(input("Enter No of Items:"))
for i in range(n):
    lst1=input(f"Enter Value{i+1}:")
    lst.append(lst1)
print(lst)
for i in lst:
    a=len(i)
    print(a)
l=int(input("Enter number:"))
for i in lst:   
    if len(i)>l:
        print(i,end="")


Enter No of Items: 4
Enter Value1: the
Enter Value2: quick
Enter Value3: brown
Enter Value4: fox


['the', 'quick', 'brown', 'fox']
3
5
5
3


Enter number: 3


quickbrown

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>3.Create an empty set. Fill the set with values by getting user input. Check if a given
value is present in a set or not.</p></b>
</body>
</html>

In [3]:
set1=set()
n=int(input("Enter the no of values:"))
for i in range(n):
    s=input(f"Enter Value{i+1}: ")
    set1.add(s)
print(set1)

search=input("Enter the value to search:")
if search in set1:
    print(search,"is present in the set")
else:
    print("Not present in set1")



Enter the no of values: 4
Enter Value1:  Audi
Enter Value2:  Benz
Enter Value3:  Toyota
Enter Value4:  BMW


{'Toyota', 'BMW', 'Audi', 'Benz'}


Enter the value to search: Audi


Audi is present in the set


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>4.Create an empty tuple. Populate the tuple with values by getting user input. Count the
occurrence of a given input number in the tuple.</p></b>
</body>
</html>

In [4]:
t = ()
n = int(input("Enter the number of inputs: "))
for i in range(n):
    t1 = input(f"Enter value {i+1}: ")
    t += (t1,)
print(t)
c = input("Enter the value to count: ")
print(t.count(c))


Enter the number of inputs:  5
Enter value 1:  50
Enter value 2:  60
Enter value 3:  10
Enter value 4:  70
Enter value 5:  50


('50', '60', '10', '70', '50')


Enter the value to count:  50


2


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>5.Create a 2D array and perform matrix subtraction using numpy.</p></b>
</body>
</html>

In [5]:
import numpy as np

m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = m1 - m2
print("Matrix 1:",m1)
print("Matrix 2:",m2)
print("Result of Matrix Subtraction:")
print(result)

Matrix 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2: [[9 8 7]
 [6 5 4]
 [3 2 1]]
Result of Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>6.Create a 2D array using numpy and find the maximum element in the matrix.</p></b>
</body>
</html>

In [6]:
import numpy as np

m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 25, 9]])
print("Matrix 1:")
print(m1)
data=np.max(m1)
print(data)

Matrix 1:
[[ 1  2  3]
 [ 4  5  6]
 [ 7 25  9]]
25


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <b><p>7.Download the dataset from https://www.kaggle.com/datasets/varshamannem/toyato.<br>
Read the Toyota.csv file and display the basic details.<br>
a. Display the top 10 rows<br>
b. Display the last 5 rows<br>
c. Display row and column details<br.
d. Display size, shape, dimension and information summary</p></b>
</body>
</html>

In [7]:
import pandas as pd
df = pd.read_csv("Employee.csv")
print("Top 10 rows:")
print(df.head(10))
print("Last 5 rows:",df.tail(5))

print("\nRow and Column Details:")
print(f'Number of rows: {df.shape[0]}')
print(f'Number of columns: {df.shape[1]}')
print("\nSize, Shape, Dimension, and Information Summary:")
print(f'Size: {df.size}')
print(f'Shape: {df.shape}')
print(f'Dimension: {df.ndim}')
print(df.info())



Top 10 rows:
  fEducation  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   
5  Bachelors         2016  Bangalore            3   22    Male          No   
6  Bachelors         2015  New Delhi            3   38    Male          No   
7  Bachelors         2016  Bangalore            3   34  Female          No   
8  Bachelors         2016       Pune            3   23    Male          No   
9    Masters         2017  New Delhi            2   37    Male          No   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
    <h2>Result:</h2>
    <p>Operations Using Set,Tuples,list,Dictionary and Acessing the CSV File have been executed Sucessfully</p>
</body>
</html>